name: feature-branch
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node modules
        run: npm ci
      - name: Test
        run: npm run test
